name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 #it is going to create a local copy then go to runner and check if the code is error free
    - name: Set up JDK 17
      uses: actions/setup-java@v4 #setup the java environment
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Make Maven
      run: chmod +x mvnw
